version: '3.7'

services:

  cryptocerts-client:
    container_name: cryptocerts-client
    build:
      context: .
      dockerfile: Dockerfile
    image: cryptocerts-client-image
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true0